---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: pod1
      image: docker.io/centos/tools:latest
      command:
        - /sbin/init
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
    - name: pod2
      image: docker.io/centos/tools:latest
      command:
        - /sbin/init
