apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: grafana
 namespace: monitoring
spec:
 rules:
 - host: grafana.cluster
   http:
     paths:
     - path: /
       backend:
        serviceName: grafana
        servicePort: 3000
